services:
  web:
    build: .
    container_name: devops-web
    ports:
      - "5001:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: devops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_task_manager
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: